### ISSUE TITLE
"add address" example does not compile: set_name_filter missing

### ISSUE THREAD

**Issue by igor-petruk** [little-dude/netlink#61] opened 2019-12-15 11:01 UTC
Additional datapoint: try searching for this method here

https://docs.rs/rtnetlink/0.1.1/rtnetlink/?search=set_name_filter

Aslo not there. I wonder if the crate 0.1.1 was released from some older version of the code, where this method was not there yet

**Comment by wllenyj** [comment] 2020-01-08 08:58
Maybe the author has not cargo published. 
The same problem is 
```
error[E0599]: no function or associated item named `default` found for type `netlink_packet_route::rtnl::route::message::RouteMessage` in the current scope
  --> /home/wanglei01/opt/work/kata/netlink-rs/src/route/add.rs:17:41           
   |                                                    
17 |         let mut message = RouteMessage::default();
   |                                         ^^^^^^^ function or associated item not found in `netlink_packet_route::rtnl::route::message::RouteMessage`

error[E0308]: mismatched types
  --> /home/wanglei01/opt/work/kata/netlink-rs/src/route/add.rs:43:37
   |                                                    
43 |         self.message.header.table = table;
   |                                     ^^^^^
   |                                     |
   |                                     expected enum `netlink_packet_route::rtnl::route::header::RouteTable`, found u8
   |                                     help: try using a variant of the expected enum: `netlink_packet_route::rtnl::route::header::RouteTable::Unknown(table)`
   |                                                    
   = note: expected type `netlink_packet_route::rtnl::route::header::RouteTable`
              found type `u8`
```

**Comment by little-dude** [comment] 2020-01-08 19:36
Sorry for being so little reactive on this. @igor-petruk I published `rtnetlink` 0.2 a while ago which should solve the problem.

@wllenyj I'm quite confused by your error. It seems that indeed the `netlink-packet-route` package I uploaded is slightly different from what is currently in master. `RouteMessage` doesn't implement `Default` for instance: https://docs.rs/netlink-packet-route/0.1.0/src/netlink_packet_route/rtnl/route/message.rs.html#9-12

**Comment by little-dude** [comment] 2020-01-08 19:42
@wllenyj @igor-petruk can you tell me exactly what you're trying to build, so that I can reproduce? I assume you're not building the examples directly from the repo.

**Comment by little-dude** [comment] 2020-01-08 19:49
Just released `netlink-packet-route` 0.1.1 and `rtnetlink` 0.2.1. Can you `cargo update` and tell me if that fixes your problem?

**Comment by wllenyj** [comment] 2020-01-09 05:21
I'm sorry to make you confused. 
I 'm trying to build a synchronous version of rtnetlink, so I will use  `netlink-packet-route` and  `netlink-sys` directly. 
Now I `cargo update` to `netlink-packet-route 0.1.1` and `rtnetlink 0.2.1`, It 's good. 
Thanks very much.

**Comment by little-dude** [comment] 2020-01-09 08:36
> I 'm trying to build a synchronous version of rtnetlink

Oh very cool. Let me know how it goes I'm pretty interested in this.

**Comment by wllenyj** [comment] 2020-01-09 12:51
It's very simple. I just use `netlink-packet-route/examples/dump_links.rs` to implement a Handle struct, that is a wrap for `netlink-sys::Socket`. And implement a request function using sync call `Socket`.  The other eg. LinkHandle still use `rtnetlink`, just call the request of `Handle` instead of async in execute. 
My team is very concerned about the dependencies of crate . So don't want to use tokio.

**Comment by little-dude** [comment] 2020-02-16 10:51
Closing, since the initial issue seems to have been fixed.

**Closed by little-dude** 2020-02-16 10:51 UTC
