### ISSUE TITLE
Unknown packet types silently discarded

### ISSUE THREAD

**Issue by jethrogb** [little-dude/netlink#64] opened 2020-02-06 14:34 UTC
I tried to use rule (which I now found out is not supported #5), but any unknown packets are simply discarded instead of an error being returned on the stream.

**Comment by little-dude** [comment] 2020-02-06 15:12
Hello @jethrogb 

I would need a little bit more context to help. Could you share the code you're trying to run?

**Comment by jethrogb** [comment] 2020-02-06 15:25
```
#[tokio::main]
async fn main() {
    let (mut c, _, mut r) = rtnetlink::new_connection().unwrap();

    let addr = netlink_sys::SocketAddr::new(0, rtnetlink::constants::RTMGRP_IPV4_RULE);

    c.socket_mut().bind(&addr).unwrap();
    tokio::spawn(c);

    loop {
        println!("{:?}", r.next().await.unwrap());
    }
}
```

Then make a rule change with `ip rule`, notice nothing happens

**Comment by hermantolim** [comment] 2020-02-27 05:48
@jethrogb I tried current master branch, and I am unable to reproduce this issue. Could you tell me which version are you using?

**Comment by little-dude** [comment] 2021-01-20 19:46
Closing since it's unclear whether there's really a bug.

**Closed by little-dude** 2021-01-20 19:46 UTC
Labels: needs-more-info
